server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: cirtuit-breaker
          uri: https://github.com/RafaelRFP/Microservice-LCProject
          search-paths: config-data
  application:
    name: config-service

